### ISSUE TITLE
View and alert resource import support

### ISSUE THREAD

**Issue by jsoh** [logdna/terraform-provider-logdna#13]
The current version 1.0.0 of the provider does not appear to support importing of existing view or alert resources:

https://registry.terraform.io/providers/logdna/logdna/latest/docs/resources/logdna_view

Are there any plans to support this feature?

**Comment by dm36** [comment]
hi @jsoh! There are plans to support imports for views and alert resources (as well as support for drift https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform)- there is a pr currently in draft that can be found here (https://github.com/logdna/terraform-provider-logdna/pull/10/files). The pr depends upon on the get endpoint for the configuration-api which will be released this coming week

**Comment by mdeltito** [comment]
This is available in `v1.2.0` via 854b57bcffb9f0e8adda8a9418e86dcae08c2a80 🎉
