### ISSUE TITLE
Slack alert channel support

### ISSUE THREAD

**Issue by jsoh** [logdna/terraform-provider-logdna#14]
Reading through the source, I only see support for email, pagerduty, and webhoot. Are there plans to support Slack alert channels? 

https://github.com/logdna/terraform-provider-logdna/blob/main/logdna/resource_alert.go

**Comment by dm36** [comment]
@jsoh hi jimmy- thank you for your interest!! That is correct- we currently support email, pagerduty and webhook via the provider and we do plan to expand support to Slack alert channels

**Comment by philippfrank** [comment]
@dm36 Is this something that still could be expected?

**Comment by mdeltito** [comment]
@philippfrank yes, support for Slack as an alerting channel is still planned in our backlog

**Comment by mdeltito** [comment]
@jsoh @philippfrank one thing worth noting is that if you configure a `webhook` channel using the Slack webhook URL `hooks.slack.com`, you can accomplish essentially the same integration today. We do still plan to evaluate more explicit support for Slack (among other integrations) in the provider as well, but this might be a good solution in the meantime.

**Comment by isibeni** [comment]
@mdeltito Can you provide an example on how this can be accomplished to achieve basically the same result as with the "native" slack channel

**Comment by philippfrank** [comment]
@mdeltito It is unnecessary complex though. The provider does already allow to define a (reusable) slack alert channel. Why isn't there a way to attach that channel to a view?

**Comment by mdeltito** [comment]
@philippfrank the `slack_channel` type was added after my comment above, we do now support that as a first-class channel type in the provider. it sounds like your other bug report is addressing a different concern, we'll take a look 👍
