### ISSUE TITLE
Support for adding categories

### ISSUE THREAD

**Issue by isibeni** [logdna/terraform-provider-logdna#30]
Currently it's not possible to create new view categories.
A manual step is needed before I can create my view via terraform.

It would be helpful if we the provider would be able to directly create and mange categories

**Comment by l2fprod** [comment]
@seeruyy 

looks like this was delivered? https://registry.terraform.io/providers/logdna/logdna/latest/docs/resources/logdna_category

**Comment by seeruyy** [comment]
@l2fprod Yes, we released this enhancement in 1.8.0 version.
