### ISSUE TITLE
Bug: provider will update resources in place when they have slack channels attached

### ISSUE THREAD

**Issue by philippfrank** [logdna/terraform-provider-logdna#40]
I use the provider to create:
* a view
* a slack alert channel

Since there seems no way to attach the alert to the view yet (see https://github.com/logdna/terraform-provider-logdna/issues/26 and https://github.com/logdna/terraform-provider-logdna/issues/14), I have to attach the slack alert channel via the user interface.

Whenever I now run `terraform apply`, it will attempt to modify the view resources, detaching the slack channel. This is very frustrating.

![image](https://user-images.githubusercontent.com/1238801/148403686-adcd01b7-eeaa-4779-b75b-0729070a6178.png)

**Comment by mdeltito** [comment]
@philippfrank we have added alerts as a Data Source, which should allow for the workflow you are looking for using Alert Presets:

https://registry.terraform.io/providers/logdna/logdna/latest/docs/data-sources/logdna_alert

**Comment by mdeltito** [comment]
ah I see your other comment about using a preset not working for `slack_channel`. that's unexpected, and something we can look into

**Comment by philippfrank** [comment]
Maybe I am misunderstanding presets. Question: when I use the web user interface and attach a previously created channel (slack, PD etc.) to a view, what happens internally? Are you "making a copy" of the preset params and attach that to the view. Or, are you referencing the ID of that preset from the view? In either case, as [others](https://github.com/logdna/terraform-provider-logdna/issues/26#issuecomment-889902117) have pointed out, it's not clear what's happening.

@david-ly's [answer](https://github.com/logdna/terraform-provider-logdna/issues/26#issuecomment-956394377) does not work, see my other comment.

**Comment by gjanco** [comment]
@philippfrank , we have added this request to our backlog.  Our intention is to have a `presetid` as an option instead of a channel.  This way you could either refer to an existing preset alert you created in the UI, or use TF state variables to set this value to an alert you created in TF.

**Comment by philippfrank** [comment]
@gjanco This is great, thanks for the update. Looking forward to the release, count me in for testing ;)

**Comment by gjanco** [comment]
Closing this issue as it will be addressed by #26
