### ISSUE TITLE
Preserve live tail and alert in Exclusion Rules

### ISSUE THREAD

**Issue by marcelomanchester** [logdna/terraform-provider-logdna#48]
Hey!

I've created some exclusion rules using the provider (1.8.0), but I couldn't preserve live tail and alerts for these rules. That's possible [when creating the rules through browser](https://docs.logdna.com/docs/excluding-log-lines).

It would be helpful if the provider would be able to enable this.

I enjoy working with LogDNA, mainly because of this provider :)

**Comment by isibeni** [comment]
any news on this?

**Comment by gjanco** [comment]
Sorry for the delay.  We will be working on this shortly.  We will close this issue once we have fixed this.

**Comment by jsumners** [comment]
We have added support for the `indexonly` attribute in 1.13.0. Please let us know if you encounter any issues.
