### ISSUE TITLE
Support for auto-resolve

### ISSUE THREAD

**Issue by renier** [logdna/terraform-provider-logdna#67]
You currently can set alerts to auto-resolve in the logDNA UI, however that capability is not exposed via the `logdna_alert` resource.

I would expect the channel map to accept an `autoresolve = <bool>` option, with the additional corresponding triggers. Behind the scenes I understand this becomes two channels: the main one, and another one suffixed with `-auto-resolve`. The main channel then points to the auto resolve channel via the autoresolveid value.

Would be a great feature add.

**Comment by gjanco** [comment]
Thank you for your patience.  It is officially on our roadmap to expose this property.  I don't have an exact timeline, but will post here when this is available.

**Comment by gjanco** [comment]
This is now fixed and available in https://github.com/logdna/terraform-provider-logdna/releases/tag/v1.15.0
